- Package.resolved
- Package.swift
- Sources/Compound/Text Field Styles/SearchFieldStyle.swift
This PR updates Introspect to the latest version, uses the newer API (the previous ones have been deprecated, slated for removal in 1.0) and adds a change to `compoundSearchField()` that will keep the navigation bar visible during a search in a modal.
> Keep navigation bar visible when searching in a modal.

- Inspector/Sources/Components/FormScreen.swift
- Sources/Compound/Form Styles/FormRowLabelStyle.swift
- Sources/Compound/Form Styles/FormStyles.swift
This PR matches the form row insets (and minimum row height) to the designs in Figma.
One issue that came up was `Toggle` and `Picker` would ignore the vertical insets at certain content sizes (I think there's some magic going on to allow the switch to escape the insets). To fix this, I've confirmed the desired behaviour with @janogarcia and the fix was to zero the vertical insets, replacing this with vertical padding on the label.
> Fix row insets.

- .github/workflows/tests.yml
- Sources/Compound/Colors/CompoundColors.swift
- Tests/CompoundTests/AvatarColorsTests.swift
In this PR I added the new avatar colors (which are now separated into background and foreground), improved the hashing function to match web, and included the same test that web uses to check the matching of the original string with the hashed color.
The PR also uses the same 8 colors as web, even if we are planning to only use 6 in the future.
> New avatar colors + tests

- Sources/Compound/Form Styles/FormButtonStyle.swift
- Sources/Compound/Icons/CompoundIcon.swift
- Sources/Compound/List/ListRowAccessory.swift
This PR stops using the font size to scale a Compound icon, instead adding a dedicated `Size` enum with the 3 pre-defined icon sizes.
Font styles are still used to determine rescaling with Dynamic Type.
> Add CompoundIcon.Size.

- Inspector/Inspector.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Inspector/Sources/CompoundInspectorApp.swift
- Inspector/Sources/System Components/ActionSheetScreen.swift
- Inspector/Sources/System Components/AlertScreen.swift
- Sources/Compound/Text Field Styles/SearchFieldStyle.swift
Turns out that `v17` is chosen when building with the iOS 16 SDK 🤦‍♂️
I've tested all of these and they behave as expected on the iOS 17 simulator when compiling with Xcode 14.3.
> Add iOS 17 window and navigationStack introspections.

- Package.swift
We haven't decided if we want this in Compound or EX yet, and it causes CI issues in places we probably shouldn't be blank enabling plugins to run.
> Remove playbook plugin from the target for now.

- Inspector/Inspector.xcodeproj/project.pbxproj
- Inspector/Sources/Components/ButtonsScreen.swift
- Sources/Compound/BaseStyles/CompoundButtonStyle.swift
- Sources/Compound/Colors/CompoundColors.swift
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_compoundButtonStyle.1.png
This PR merges `ElementActionButtonStyle` and `ElementCapsuleButtonStyle` from DesignKit into a single style.
There are no official button styles defined in Compound yet, however this follows Android for naming as we'll likely be aligned with that [component](https://www.figma.com/file/G1xy0HDZKJf5TCRFmKb5d5/Compound-Android-Components?type=design&node-id=854-64108&mode=dev).
There shouldn't be any visual difference between the at-rest implementations (but disabled and pressed states have been updated to use the respective colour tokens where available).
> Add CompoundButtonStyle from Element X

- .gitattributes
- .github/workflows/tests.yml
- .gitmodules
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_compoundButtonStyle.1.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_compoundIcon.Accessibility-Icons-Only.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_compoundIcon.Accessibility-Labels.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_compoundIcon.Buttons.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_compoundIcon.Form.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_compoundToggleStyle.1.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_listDetailsLabel.1.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_listInlinePicker.1.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_listLabel.1.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_listRow.1.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_listRowButtonStyle.1.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_listTextStyles.Form.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_listTextStyles.List.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_searchStyle.Form.png
- Tests/CompoundTests/__Snapshots__/PreviewTests/test_searchStyle.List.png
- Tests/PreviewTests.stencil
This PR move the snapshots from LFS in this repo, into LFS inside of https://github.com/vector-im/compound-ios-snapshots that is added as a submodule. This fixes checkout errors when using the package inside of Xcode.
> Move snapshots into submodule

- .gitmodules
Turns out using ssh doesn't work on CI without more setup involved, this is probably better.
> Switch submodule to https

- Inspector/Sources/SidebarList.swift
Small follow-up from https://github.com/vector-im/compound/issues/125, this PR adds an extra section in the Inspector to highlight when components don't have designs yet.
> Clarify when components aren't yet in Figma.

- Sources/Compound/List/ListDetailsLabel.swift
- Sources/Compound/List/ListLabel.swift
Allows us to use
```swift
ListRow(label: .default(blah, icon: \.settings), …)
```
as a shortcut for
```swift
ListRow(label: .default(blah, icon: CompoundIcon(\.settings)), …)
```
> Add convenience initialisers for icons on ListRow.

- Sources/Compound/List/ListRow.swift
- Sources/Compound/List/ListRowAccessory.swift
Make sure the checkmark space is reserved so that this doesn't happen:
https://github.com/vector-im/compound-ios/assets/6060466/f776a87b-0420-4fb7-a488-e4c66c691a71
> Fix layout when changing selection in a list.

- Sources/Compound/BaseStyles/CompoundTextFieldStyles.swift
- Sources/Compound/List/ListRow.swift
- Fix the introspection of a text field in a list row (it was backed by a `UITextView` so was acting like a text editor by mistake)
- Add the toggle accessibility trait on iOS 17.
- Make the text field placeholder style reusable.
> A couple of minor tweaks.

- Inspector/Inspector.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.resolved
- Package.swift
This PR pulls in the latest version of the design tokens package. Its updates the icons and adds new decorative colours. The decorative colours will be a follow-up PR that we can do at the same time as Web and Android (as they replace avatar colours and reduce the number of options from 8 to 6).
A few snapshots needed regenerating for the latest round of icon updates - you can't see the change in the diffs which is a bit surprising given we have lowered perceptual precision 🤷‍♂️
> Update design tokens.

- .github/workflows/tests.yml
- codecov.yml
The PR adds the codecov action after running unit tests.
> Add codecov to unit tests.

- Sources/Compound/Colors/CompoundColors.swift
- Sources/Compound/List/ListRow.swift
- Sources/Compound/List/ListRowLabel.swift
- Tests/CompoundTests/AvatarColorsTests.swift
These new semantic tokens were added for avatars, displaynames etc so we don't need to hard-code against the base colours any more 🎉
EX PR here: https://github.com/element-hq/element-x-ios/pull/2438
> Adopt new decorative colour tokens to align with Web.

- Sources/Compound/List/ListRowAccessory.swift
https://www.figma.com/file/ux3tYoZV9WghC7hHT9Fhk0/Compound-iOS-Components?type=design&node-id=1974-2771&mode=dev
> Update ListRow multiSelection to match Figma.

- .github/workflows/tests.yml
Codecov got a report with this change: https://app.codecov.io/github/element-hq/compound-ios/pull/69
Compared to builds made in the last 2 weeks:
> Codecov: Move to codecov-action v4 and fix coverage report

- Inspector/Inspector.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Inspector/Sources/Tokens/AllCases.swift
- Inspector/Sources/Tokens/FontsScreen.swift
- Inspector/Sources/Tokens/IconsScreen.swift
- Package.resolved
- Package.swift
- Sources/Compound/Colors/CompoundColors.swift
- Sources/Compound/Colors/CompoundUIColors.swift
- Tests/CompoundTests/AvatarColorsTests.swift
- Tests/CompoundTests/OverrideColorTests.swift
Can be reviewed commit-by-commit, this PR adopts the [new token format](https://github.com/element-hq/compound-design-tokens/pull/86) for semantic tokens and uses these to allow runtime customisation of the colours. Some beautiful examples of this working:
| | |
| - | - |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-07-09 at 16 18 37](https://github.com/element-hq/compound-ios/assets/6060466/31e5bd7e-a227-4ee3-9a6b-549766b2592e) | ![Simulator Screenshot - iPhone 15 Pro - 2024-07-09 at 16 18 59](https://github.com/element-hq/compound-ios/assets/6060466/ec0341b6-11ce-4608-aa32-1892a5be5937) |
> Add support for customising specific colours.

- Inspector/Inspector.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.resolved
- Package.swift
- Sources/Compound/List/ListRow.swift
They now correctly use `.textDisabled` (and `.textPrimary` when enabled).
> Fix the text colour of ListRow text fields when disabled.

- .github/workflows/tests.yml
- Tests/CompoundTests/.prefire.yml
- Tests/CompoundTests/PreviewTests.stencil
Uses iPhone SE 3rd Generation for snapshots to match EX.
> Update the project to use Xcode 15.4.

- .github/workflows/tests.yml
- Sources/Compound/List/ListRow.swift
- Sources/Compound/List/ListRowLabel.swift
- Tests/CompoundTests/.prefire.yml
- Tests/CompoundTests/PreviewTests.stencil
- Update test workflow to use Xcode 16 and and iOS 18 simulator.
- Unrelated but I had to regenerate all the snapshots so I fixed any that were being truncated.
> Upgrade the project to use Xcode 16.0

- .github/workflows/tests.yml
The macOS-14 runner has the final Xcode binary in the image now.
> Use the final version of Xcode 16 on CI.

- Sources/Compound/BaseStyles/CompoundButtonStyle.swift
Our secondary buttons weren't using the correct border colour, this PR fixes that.
| Before | After |
| - | - |
| <img width="375" alt="old" src="https://github.com/user-attachments/assets/1ce45f35-99b2-4e58-999b-8255d8b89b6d"> | <img width="375" alt="new" src="https://github.com/user-attachments/assets/4f57d4ee-5966-42a4-bb49-06b521b215b2"> |
> Update the stroke colour of the secondary button style to match Figma.

- Sources/Compound/BaseStyles/CompoundButtonStyle.swift
Enabling the Button Shapes accessibility option will now underline our `plain` button style (which we use for both the Tertiary and Text Link) components as we haven't updated for this distinction yet.
| Button Shapes on | Button Shapes off |
| - | - |
| ![IMG_9F41B7C3EF57-1](https://github.com/user-attachments/assets/d03fb138-b9f4-4199-9bdd-9c3127a151ca) | ![IMG_B8CDAB240E4F-1](https://github.com/user-attachments/assets/c9a340fe-a8ba-40a4-b5dd-7798b8a43961) |
> Underline plain buttons when button shapes are enabled.

- Sources/Compound/Buttons/SendButton.swift
- Sources/Compound/Fonts/CompoundFonts.swift
- Sources/Compound/Layout/ScaledFrameModifier.swift
- Sources/Compound/Layout/ScaledOffsetModifier.swift
- Sources/Compound/Layout/ScaledPaddingModifier.swift
Compared to the rest of the ComposerToolbar, the button wasn't scaling relative to the `.title` text style. This PR
- Adds all of our `scaledPadding`/`Offset`/`Frame` modifiers.
- Along with some snapshot tests of each proving they work.
- Adds a compound text style mapping.
- Uses `.compound.headingLG` to scale the button (which maps to `.title`).
> Fix the send button when using Dynamic Type

- Sources/Compound/Buttons/SendButton.swift
- Sources/Compound/Colors/CompoundColors.swift
> Update to the new SendButton design.

- Sources/Compound/Buttons/SendButton.swift
Use `light/icon/on-solid-primary` instead of `dark/icon/primary` in light mode. This also removes the need to override the colour scheme now seeing as the gradient isn't using reactive colours either.
It's hard to see but there is a difference to the light mode compared to #130:
> Fix a colour token in light mode on the SendButton.

- .github/workflows/tests.yml
This is the Compound version of https://github.com/element-hq/element-x-ios/pull/3908
> Pin 3rd-party GitHub actions to their commit SHA.

- Sources/Compound/List/ListRow.swift
`LabeledContent` did not properly group accessibility elements by default, so we need to manually apply the modifier ourselves.
> Fix: accessibility on toggles and pickers in lists

- Inspector/Inspector.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.resolved
- Package.swift
- Sources/Compound/Colors/CompoundColors.swift
- Sources/Compound/Colors/CompoundUIColors.swift
https://github.com/element-hq/compound-design-tokens/pull/170 fixed the bug where asymmetric tokens weren't generated properly. This means we can get rid of those manually created ones and overrides will all work properly!
> Use the generated asymmetric tokens 🎉

- Sources/Compound/Colors/CompoundGradients.swift
All the other colours were reacting to multiple runtime colour overrides in Element X but the gradients were not 🤦‍♂️
> Make the gradients computed so they react to colour token overrides.
